//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacultyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public int FacultyId { get; set; }
        public string FacultyName { get; set; }
        public string Email { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string ImageName { get; set; }
        public string ImageUrl { get; set; }
        public int CourseId { get; set; }
        public virtual Course Course { get; set; }
    }
}
